<a href="https://colab.research.google.com/github/Prithibee13/basicnumpy/blob/main/basicnum.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as num

A = num.array(42)
B = num.array([1,2,3,4,5])
C = num.array([[1,2,3,4,5],[10,20,30,40,50]])
D = num.array([[[1,2,3,4,5],[10,20,30,40,50]],[[100,200,300,400,500],[1000,2000,3000,4000,5000]]])
E = num.array([1,2,3,4,5],ndmin=5)
F = num.array([1,2,3,4,5], dtype='S')
G = num.array([1,2,3,4,5], dtype='i4')
H = num.array([1.1,2.2,3.3,4.4,5.5])
I = num.array([0,1,0,2])

newH = H.astype(int)
NewI = I.astype(bool)


print(A)
print(B)
print(C)
print(D)
print(E)
print(A.ndim)
print(B.ndim)
print(C.ndim)
print(D.ndim)
print(B[0])
print(B[2]+B[3])
print(C[0,1])
print(C[1,4])
print(D[0,1,2])
print(C[-0,-1])
print(B[1:5])
print(B[4:])
print(B[:4])
print(B[-3:-1])
print(B[1:5:2])
print(B[::2])
print(C[1, 1:4])
print(C[0:2, 2])
print(C[0:2, 0:3])
print(B.dtype)
print(F)
print(F.dtype)
print(G)
print(G.dtype)
print(newH)
print(NewI)

42
[1 2 3 4 5]
[[ 1  2  3  4  5]
 [10 20 30 40 50]]
[[[   1    2    3    4    5]
  [  10   20   30   40   50]]

 [[ 100  200  300  400  500]
  [1000 2000 3000 4000 5000]]]
[[[[[1 2 3 4 5]]]]]
0
1
2
3
1
7
2
50
30
5
[2 3 4 5]
[5]
[1 2 3 4]
[3 4]
[2 4]
[1 3 5]
[20 30 40]
[ 3 30]
[[ 1  2  3]
 [10 20 30]]
int64
[b'1' b'2' b'3' b'4' b'5']
|S1
[1 2 3 4 5]
int32
[1 2 3 4 5]
[False  True False  True]
